version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: webhook_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - redis
    env_file:
      - .env

  beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
